package com.blackrobot.bestgarden;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APLICACION.
 */
public class Aplicacion {

    private Long id;
    private int zid_aplicacion;
    private String zepoca_anual;
    private String zdosificacion;
    private String zfrecuencia;
    private String zetapa;
    private Integer zid_planta;
    private Integer zid_plaga;
    private Integer zid_producto;

    public Aplicacion() {
    }

    public Aplicacion(Long id) {
        this.id = id;
    }

    public Aplicacion(Long id, int zid_aplicacion, String zepoca_anual, String zdosificacion, String zfrecuencia, String zetapa, Integer zid_planta, Integer zid_plaga, Integer zid_producto) {
        this.id = id;
        this.zid_aplicacion = zid_aplicacion;
        this.zepoca_anual = zepoca_anual;
        this.zdosificacion = zdosificacion;
        this.zfrecuencia = zfrecuencia;
        this.zetapa = zetapa;
        this.zid_planta = zid_planta;
        this.zid_plaga = zid_plaga;
        this.zid_producto = zid_producto;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getZid_aplicacion() {
        return zid_aplicacion;
    }

    public void setZid_aplicacion(int zid_aplicacion) {
        this.zid_aplicacion = zid_aplicacion;
    }

    public String getZepoca_anual() {
        return zepoca_anual;
    }

    public void setZepoca_anual(String zepoca_anual) {
        this.zepoca_anual = zepoca_anual;
    }

    public String getZdosificacion() {
        return zdosificacion;
    }

    public void setZdosificacion(String zdosificacion) {
        this.zdosificacion = zdosificacion;
    }

    public String getZfrecuencia() {
        return zfrecuencia;
    }

    public void setZfrecuencia(String zfrecuencia) {
        this.zfrecuencia = zfrecuencia;
    }

    public String getZetapa() {
        return zetapa;
    }

    public void setZetapa(String zetapa) {
        this.zetapa = zetapa;
    }

    public Integer getZid_planta() {
        return zid_planta;
    }

    public void setZid_planta(Integer zid_planta) {
        this.zid_planta = zid_planta;
    }

    public Integer getZid_plaga() {
        return zid_plaga;
    }

    public void setZid_plaga(Integer zid_plaga) {
        this.zid_plaga = zid_plaga;
    }

    public Integer getZid_producto() {
        return zid_producto;
    }

    public void setZid_producto(Integer zid_producto) {
        this.zid_producto = zid_producto;
    }

}
