package com.blackrobot.bestgarden;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.blackrobot.bestgarden.Planta;
import com.blackrobot.bestgarden.Plaga;
import com.blackrobot.bestgarden.Aplicacion;
import com.blackrobot.bestgarden.Producto;

import com.blackrobot.bestgarden.PlantaDao;
import com.blackrobot.bestgarden.PlagaDao;
import com.blackrobot.bestgarden.AplicacionDao;
import com.blackrobot.bestgarden.ProductoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig plantaDaoConfig;
    private final DaoConfig plagaDaoConfig;
    private final DaoConfig aplicacionDaoConfig;
    private final DaoConfig productoDaoConfig;

    private final PlantaDao plantaDao;
    private final PlagaDao plagaDao;
    private final AplicacionDao aplicacionDao;
    private final ProductoDao productoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        plantaDaoConfig = daoConfigMap.get(PlantaDao.class).clone();
        plantaDaoConfig.initIdentityScope(type);

        plagaDaoConfig = daoConfigMap.get(PlagaDao.class).clone();
        plagaDaoConfig.initIdentityScope(type);

        aplicacionDaoConfig = daoConfigMap.get(AplicacionDao.class).clone();
        aplicacionDaoConfig.initIdentityScope(type);

        productoDaoConfig = daoConfigMap.get(ProductoDao.class).clone();
        productoDaoConfig.initIdentityScope(type);

        plantaDao = new PlantaDao(plantaDaoConfig, this);
        plagaDao = new PlagaDao(plagaDaoConfig, this);
        aplicacionDao = new AplicacionDao(aplicacionDaoConfig, this);
        productoDao = new ProductoDao(productoDaoConfig, this);

        registerDao(Planta.class, plantaDao);
        registerDao(Plaga.class, plagaDao);
        registerDao(Aplicacion.class, aplicacionDao);
        registerDao(Producto.class, productoDao);
    }
    
    public void clear() {
        plantaDaoConfig.getIdentityScope().clear();
        plagaDaoConfig.getIdentityScope().clear();
        aplicacionDaoConfig.getIdentityScope().clear();
        productoDaoConfig.getIdentityScope().clear();
    }

    public PlantaDao getPlantaDao() {
        return plantaDao;
    }

    public PlagaDao getPlagaDao() {
        return plagaDao;
    }

    public AplicacionDao getAplicacionDao() {
        return aplicacionDao;
    }

    public ProductoDao getProductoDao() {
        return productoDao;
    }

}
