package com.blackrobot.bestgarden;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAGA.
 */
public class Plaga {

    private Long id;
    private int zid_planta;
    private String znombre;
    private String zdescripcion;

    public Plaga() {
    }

    public Plaga(Long id) {
        this.id = id;
    }

    public Plaga(Long id, int zid_planta, String znombre, String zdescripcion) {
        this.id = id;
        this.zid_planta = zid_planta;
        this.znombre = znombre;
        this.zdescripcion = zdescripcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getZid_planta() {
        return zid_planta;
    }

    public void setZid_planta(int zid_planta) {
        this.zid_planta = zid_planta;
    }

    public String getZnombre() {
        return znombre;
    }

    public void setZnombre(String znombre) {
        this.znombre = znombre;
    }

    public String getZdescripcion() {
        return zdescripcion;
    }

    public void setZdescripcion(String zdescripcion) {
        this.zdescripcion = zdescripcion;
    }

}
