package com.blackrobot.bestgarden;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.blackrobot.bestgarden.Planta;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLANTA.
*/
public class PlantaDao extends AbstractDao<Planta, Long> {

    public static final String TABLENAME = "PLANTA";

    /**
     * Properties of entity Planta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Zid_planta = new Property(1, int.class, "zid_planta", false, "ZID_PLANTA");
        public final static Property Znombre = new Property(2, String.class, "znombre", false, "ZNOMBRE");
        public final static Property Zdescripcion = new Property(3, String.class, "zdescripcion", false, "ZDESCRIPCION");
    };


    public PlantaDao(DaoConfig config) {
        super(config);
    }
    
    public PlantaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLANTA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ZID_PLANTA' INTEGER NOT NULL ," + // 1: zid_planta
                "'ZNOMBRE' TEXT," + // 2: znombre
                "'ZDESCRIPCION' TEXT);"); // 3: zdescripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLANTA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Planta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getZid_planta());
 
        String znombre = entity.getZnombre();
        if (znombre != null) {
            stmt.bindString(3, znombre);
        }
 
        String zdescripcion = entity.getZdescripcion();
        if (zdescripcion != null) {
            stmt.bindString(4, zdescripcion);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Planta readEntity(Cursor cursor, int offset) {
        Planta entity = new Planta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // zid_planta
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // znombre
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // zdescripcion
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Planta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setZid_planta(cursor.getInt(offset + 1));
        entity.setZnombre(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setZdescripcion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Planta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Planta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
