package com.blackrobot.bestgarden;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCTO.
 */
public class Producto {

    private Long id;
    private int zid_producto;
    private String znombre;
    private String zobjetivo;
    private String ztipo;
    private String zlink;

    public Producto() {
    }

    public Producto(Long id) {
        this.id = id;
    }

    public Producto(Long id, int zid_producto, String znombre, String zobjetivo, String ztipo, String zlink) {
        this.id = id;
        this.zid_producto = zid_producto;
        this.znombre = znombre;
        this.zobjetivo = zobjetivo;
        this.ztipo = ztipo;
        this.zlink = zlink;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getZid_producto() {
        return zid_producto;
    }

    public void setZid_producto(int zid_producto) {
        this.zid_producto = zid_producto;
    }

    public String getZnombre() {
        return znombre;
    }

    public void setZnombre(String znombre) {
        this.znombre = znombre;
    }

    public String getZobjetivo() {
        return zobjetivo;
    }

    public void setZobjetivo(String zobjetivo) {
        this.zobjetivo = zobjetivo;
    }

    public String getZtipo() {
        return ztipo;
    }

    public void setZtipo(String ztipo) {
        this.ztipo = ztipo;
    }

    public String getZlink() {
        return zlink;
    }

    public void setZlink(String zlink) {
        this.zlink = zlink;
    }

}
